export const generation_size = parseInt(process.env.GENERATION_SIZE)
export const max_change_generation = parseFloat(process.env.MAX_CHANGE_GENERATION)
export const survivors = parseInt(process.env.SURVIVORS)
export const start_time = parseInt(process.env.START_TIME)
export const time_between_generations = parseInt(process.env.TIME_BETWEEN_GENERATIONS)
export const AI_size = parseInt(process.env.AI_SIZE)
export const generation_per_stock = parseInt(process.env.GENERATION_PER_STOCK)